server:
  port: 9250

spring:
  application:
    name: apl-lms-price-exp-manage-app

  shardingsphere:
    datasource:
      names: pricebase, pricezone, explist, explist0, explist1, develop, pricedata

      pricezone:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_zone?characterEncoding=utf-8
        username: postgres
        password: 123456

      pricebase:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_base?characterEncoding=utf-8
        username: postgres
        password: 123456

      explist:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_exp_list?characterEncoding=utf-8
        username: postgres
        password: 123456

      explist0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_exp_list_0?characterEncoding=utf-8
        username: postgres
        password: 123456

      explist1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_exp_list_1?characterEncoding=utf-8
        username: postgres
        password: 123456

      pricedata:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_data?characterEncoding=utf-8
        username: postgres
        password: 123456

      develop:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.185:5432/apl_lms_price_develop?characterEncoding=utf-8
        username: postgres
        password: 123456

    sharding:
      tables:
        price_exp_list:
          actual-data-nodes: explist.price_exp_list
          #actual-data-nodes: explist$->{0..1}.price_exp_list
          #database-strategy:
          #  standard:
          #    sharding-column: id
          #    precise-algorithm-class-name: com.apl.lms.price.exp.manage.sharding.PriceExpListDbPreciseShardingAlgorithm
          #    range-algorithm-class-name: com.apl.lms.price.exp.manage.sharding.PriceExpListDbRangeShardingAlgorithm

        price_computational_formula:
          actual-data-nodes: explist.price_computational_formula

        price_exp_axis:
          actual-data-nodes: explist.price_exp_axis

        price_exp_cost:
          actual-data-nodes: explist.price_exp_cost

        price_exp_main:
          actual-data-nodes: explist.price_exp_main

        price_exp_sale:
          actual-data-nodes: explist.price_exp_sale

        price_zone:
          actual-data-nodes: pricezone.price_zone

        price_channel_category:
          actual-data-nodes: pricebase.price_channel_category

        price_fuel_charge:
          actual-data-nodes: pricebase.price_fuel_charge

        price_special_commodity:
          actual-data-nodes: pricebase.price_special_commodity

        price_surcharge:
          actual-data-nodes: pricebase.price_surcharge

        price_weight_way:
          actual-data-nodes: pricebase.price_weight_way

        price_exp_data:
          actual-data-nodes: pricedata.price_exp_data

        price_exp_remark:
          actual-data-nodes: develop.price_exp_remark

  #redis 相关配置
  redis:
    database: 1
    host: 192.168.1.185
    port: 6379
    password: 123456
    timeout: 60
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.apl.lms.price.exp.manage.mapper: debug

apl:
  swagger:
    title: LMS-快递价格管理
    description: LMS-快递价格管理
    basePackage: com.apl.lms.price.exp.manage.app.controller
    sysProduct: pms
    subSysCode: apl_lms_price_exp_list


mybatis-plus:
  mapper-locations: file:apl-lms-price-exp-manage-impl-master/apl-lms-price-exp-manage-service/src/main/resources/mapper/*.xml
  pagination:
    dialectType: postgresql
    tenantTableFilter: price_exp_main
