spring:
  application:
    name: apl-lms-price-exp-manage-app

  thymeleaf:
    cache: false

  profiles:
    include:
      common, apl-lms-price-exp-manage-app

  main:
    allow-bean-definition-overriding: true

